export const IMAGES = {
  background: require('../../assets/bg.jpg'),
  icon: {
    isBeerUnSelected: require('../../assets/categories/beer.png'),
    isBeerSelected: require('../../assets/categories/beerS.png'),
    isChickenUnSelected: require('../../assets/categories/chicken.png'),
    isChickenSelected: require('../../assets/categories/chickenS.png'),
    isChineseUnSelected: require('../../assets/categories/chinese.png'),
    isChineseSelected: require('../../assets/categories/chineseS.png'),
    isChitterlingsUnSelected: require('../../assets/categories/chitterlings.png'),
    isChitterlingsSelected: require('../../assets/categories/chitterlingsS.png'),
    isHotpotUnSelected: require('../../assets/categories/hotpot.png'),
    isHotpotSelected: require('../../assets/categories/hotpotS.png'),
    isJapaneseUnSelected: require('../../assets/categories/japanese.png'),
    isJapaneseSelected: require('../../assets/categories/japaneseS.png'),
    isKoreanUnSelected: require('../../assets/categories/korean.png'),
    isKoreanSelected: require('../../assets/categories/koreanS.png'),
    isMeatUnSelected: require('../../assets/categories/meat.png'),
    isMeatSelected: require('../../assets/categories/meatS.png'),
    isSnackBarUnSelected: require('../../assets/categories/snackBar.png'),
    isSnackBarSelected: require('../../assets/categories/snackBarS.png'),
    isWesternUnSelected: require('../../assets/categories/western.png'),
    isWesternSelected: require('../../assets/categories/westernS.png'),
    isWorldUnSelected: require('../../assets/categories/world.png'),
    isWorldSelected: require('../../assets/categories/worldS.png'),
    icBurgerUnSelected: require('../../assets/categories/burger.png'),
    icBurgerSelected: require('../../assets/categories/burgerS.png'),
  },
};
